version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '30060:3000'

  backend:
    container_name: docker-backend
    restart: always
    build: ./signupbackend
    ports:
      - '4000:4000'